<a href="https://colab.research.google.com/github/Meet200/-Algorithms-in-python/blob/master/Jester_Dataset_SVD_KNN_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install scikit-surprise

Collecting scikit-surprise
  Downloading scikit-surprise-1.1.1.tar.gz (11.8 MB)
     |████████████████████████████████| 11.8 MB 4.7 MB/s
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-surprise) (1.0.1)
Requirement already satisfied: numpy>=1.11.2 in /usr/local/lib/python3.7/dist-packages (from scikit-surprise) (1.19.5)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-surprise) (1.4.1)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.7/dist-packages (from scikit-surprise) (1.15.0)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (setup.py) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.1-cp37-cp37m-linux_x86_64.whl size=1619412 sha256=f36ea3c2036aca3aaeb86b6957a2c55379fcca60c1e419786eb4f362d82160d8
  Stored in directory: /root/.cache/pip/wheels/76/44/74/b498c42be47b2406bd27994e16c5188e337c657025ab400c1c
Successfully built scikit-surprise
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.1

In [ ]:
import numpy as np
import pandas as pd
from surprise import SVD, KNNBasic, Dataset, Reader
from surprise.model_selection import cross_validate

In [ ]:
from google.colab import drive # to import Google drive
drive.mount('/content/drive') # mounting Google drive

Mounted at /content/drive

In [ ]:
cd /content/drive/"My Drive/Colab Notebooks/Linear regression"

/content/drive/My Drive/Colab Notebooks/Linear regression

In [ ]:
df=pd.read_csv("jester-data-1_new.csv")
df=df.drop(['Number of Ratings'],axis=1)

In [ ]:
df

       UserID    J1    J2    J3    J4    J5  ...   J95   J96   J97   J98     J  J100
0          U1 -7.82  8.79 -9.66 -8.16 -7.52  ...   NaN   NaN -5.63   NaN   NaN   NaN
1          U2  4.08 -0.29  6.36  4.37 -2.38  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2          U3   NaN   NaN   NaN   NaN  9.03  ...   NaN   NaN   NaN   NaN   NaN   NaN
3          U4   NaN  8.35   NaN   NaN  1.80  ...   NaN   NaN   NaN   NaN   NaN   NaN
4          U5  8.50  4.61 -4.17 -5.39  1.36  ...  5.73  1.55  3.11  6.55  1.80  1.60
...       ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
24978  U24979  0.44  7.43  9.08  2.33  3.20  ...  8.45  9.03  6.55  8.69  8.79  7.43
24979  U24980  9.13 -8.16  8.59  9.08  0.87  ...  9.22 -8.20 -7.23 -8.59  9.13  8.45
24980  U24981   NaN   NaN   NaN   NaN -7.77  ...   NaN   NaN   NaN   NaN   NaN   NaN
24981  U24982   NaN   NaN   NaN   NaN -9.71  ...   NaN   NaN   NaN   NaN   NaN   NaN
24982  U24983  2.43  2.67 -3.98  4.27 -2.28  ...   NaN   NaN   NaN   NaN   NaN   NaN

[24983 rows x 101 columns]

In [ ]:
df2=df
df2

       UserID    J1    J2    J3    J4    J5  ...   J95   J96   J97   J98     J  J100
0          U1 -7.82  8.79 -9.66 -8.16 -7.52  ...   NaN   NaN -5.63   NaN   NaN   NaN
1          U2  4.08 -0.29  6.36  4.37 -2.38  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2          U3   NaN   NaN   NaN   NaN  9.03  ...   NaN   NaN   NaN   NaN   NaN   NaN
3          U4   NaN  8.35   NaN   NaN  1.80  ...   NaN   NaN   NaN   NaN   NaN   NaN
4          U5  8.50  4.61 -4.17 -5.39  1.36  ...  5.73  1.55  3.11  6.55  1.80  1.60
...       ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
24978  U24979  0.44  7.43  9.08  2.33  3.20  ...  8.45  9.03  6.55  8.69  8.79  7.43
24979  U24980  9.13 -8.16  8.59  9.08  0.87  ...  9.22 -8.20 -7.23 -8.59  9.13  8.45
24980  U24981   NaN   NaN   NaN   NaN -7.77  ...   NaN   NaN   NaN   NaN   NaN   NaN
24981  U24982   NaN   NaN   NaN   NaN -9.71  ...   NaN   NaN   NaN   NaN   NaN   NaN
24982  U24983  2.43  2.67 -3.98  4.27 -2.28  ...   NaN   NaN   NaN   NaN   NaN   NaN

[24983 rows x 101 columns]

In [ ]:
colname=df2.columns[1:101]

In [ ]:
df3=(df.values)   #df2[:,1:102]

In [ ]:
ratings=(df3[:,1:102].ravel())
ratings.size

2498300

In [ ]:
a=[]

for i in range (1,24984):
    a=a+[i]

In [ ]:
b=[]
for i in range(100):
  b.extend(a)

In [ ]:
b.sort()

In [ ]:
b

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 ...]

In [ ]:
jokes=[]

for i in range (1,101):
    jokes=jokes+[str(i)]

In [ ]:
users=b   #length=2498300
movies=jokes*24983   #length=2498300 

ratings_dict={'userID':users,
              'itemID':movies,
              'rating':ratings}

df=pd.DataFrame(ratings_dict)

In [ ]:
df

         userID itemID rating
0             1      1  -7.82
1             1      2   8.79
2             1      3  -9.66
3             1      4  -8.16
4             1      5  -7.52
...         ...    ...    ...
2498295   24983     96    NaN
2498296   24983     97    NaN
2498297   24983     98    NaN
2498298   24983     99    NaN
2498299   24983    100    NaN

[2498300 rows x 3 columns]

In [ ]:
df.dropna(inplace=True)

In [ ]:
df

         userID itemID rating
0             1      1  -7.82
1             1      2   8.79
2             1      3  -9.66
3             1      4  -8.16
4             1      5  -7.52
...         ...    ...    ...
2498267   24983     68   7.48
2498268   24983     69   5.15
2498269   24983     70    3.2
2498270   24983     71   6.26
2498286   24983     87   7.23

[1810455 rows x 3 columns]

In [ ]:
#remove this
newdf=df.iloc[0:1800005]

In [ ]:
newdf

         userID itemID rating
0             1      1  -7.82
1             1      2   8.79
2             1      3  -9.66
3             1      4  -8.16
4             1      5  -7.52
...         ...    ...    ...
2483747   24838     48  -7.04
2483748   24838     49  -1.07
2483749   24838     50   9.08
2483750   24838     51  -3.79
2483751   24838     52  -0.39

[1800005 rows x 3 columns]

In [ ]:
#write df in place of newdf for final run
reader=Reader(rating_scale=(-10,10))
trainset=Dataset.load_from_df(df[['userID','itemID','rating']],reader).build_full_trainset()

In [ ]:
#write df in place of newdf for final run
data=Dataset.load_from_df(df[['userID','itemID','rating']],reader)

In [ ]:
algo_svd=SVD()
algo_svd.fit(trainset)

In [ ]:
cross_validate(algo_svd,data,measures=['rmse','mae'],cv=5,verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    4.1093  4.1036  4.1086  4.1064  4.0982  4.1052  0.0040
MAE (testset)     3.1909  3.1875  3.1917  3.1864  3.1824  3.1878  0.0033
Fit time          92.68   94.18   95.43   96.15   96.17   94.92   1.33
Test time         8.26    7.96    7.94    7.81    7.47    7.89    0.25

{'fit_time': (92.68286347389221,
  94.1817216873169,
  95.42648911476135,
  96.1505777835846,
  96.16899752616882),
 'test_mae': array([3.19091571, 3.18753945, 3.19166671, 3.18644923, 3.18240796]),
 'test_rmse': array([4.10926936, 4.10356363, 4.10859251, 4.10638956, 4.09818227]),
 'test_time': (8.255650997161865,
  7.95543909072876,
  7.937620639801025,
  7.814924001693726,
  7.472771406173706)}

In [ ]:
algo_svd.predict(1,'2')

Prediction(uid=1, iid='2', r_ui=None, est=8.49274560694106, details={'was_impossible': False})

In [ ]:
algo_svd.predict(1,'1')

Prediction(uid=1, iid='1', r_ui=None, est=-2.052942061642979, details={'was_impossible': False})

In [ ]:
algo_svd.predict(1,'5')

Prediction(uid=1, iid='5', r_ui=None, est=-2.582399680581643, details={'was_impossible': False})

In [ ]:
algo_svd.predict(11094,'76')

Prediction(uid=11094, iid='76', r_ui=None, est=5.955733459372986, details={'was_impossible': False})

In [ ]:
algo_svd.predict(22094,'100')

Prediction(uid=22094, iid='100', r_ui=None, est=-7.439295283851596, details={'was_impossible': False})

In [ ]:
from surprise import KNNBasic
algo_knn=KNNBasic()
algo_knn.fit(trainset)

Computing the msd similarity matrix...

In [ ]:
cross_validate(algo_knn,data,measures=['rmse','mae'],cv=5,verbose=True)

In [ ]:
algo_knn.predict(43,'10')

In [ ]:
from surprise import SVDpp

In [ ]:
algo_SVDpp=SVDpp()
algo_SVDpp.fit(trainset)

In [ ]:
cross_validate(algo_SVDpp,data,measures=['rmse','mae'],cv=2,verbose=True)

In [ ]:
algo_SVDpp.predict(1,'1')

In [ ]:
from surprise import KNNWithMeans
algo_KNNMEANS=KNNWithMeans()
algo_KNNMEANS.fit(trainset)

In [ ]:
cross_validate(algo_KNNMEANS,data,measures=['rmse','mae'],cv=2,verbose=True)

In [ ]:
from surprise import BaselineOnly
algo_baseline=BaselineOnly()
algo_baseline.fit(trainset)

In [ ]:
cross_validate(algo_baseline,data,measures=['rmse','mae'],cv=2,verbose=True)

In [ ]:
algo_baseline.predict(1,'200')

In [ ]:
from surprise import CoClustering
algo_cocluster=CoClustering()
algo_cocluster.fit(trainset)

In [ ]:
cross_validate(algo_cocluster,data,measures=['rmse','mae'],cv=2,verbose=True)

In [ ]:
from surprise import KNNWithZScore
KNNZScore=KNNWithZScore()

In [ ]:
KNNZScore.fit(trainset)

In [ ]:
cross_validate(KNNZScore,data,measures=['rmse','mae'],cv=2,verbose=True)